### ISSUE TITLE
Charts not accessible

### ISSUE THREAD

**Issue by richardcase** [go-feature-flag/helm-charts#1]
I've just tried to use the chart and i'm seeing a 404 when using `https://charts.gofeatureflag.org/`:

![image](https://github.com/user-attachments/assets/2c6762b4-c208-46e2-ab87-8b6fc6e0ba0d)

**Comment by richardcase** [comment]
@thomaspoignant - just to let you know. Love the project by the way 🥇

**Comment by thomaspoignant** [comment]
Hello 👋  
Thanks for all the kind words about goff.
The charts are published in this repository https://github.com/go-feature-flag/helm-charts and released as GitHub pages in the domain you mentioned.

You probably get a 404 because we don’t have an index.html but if you try this address https://charts.gofeatureflag.org/index.yaml this should work.


I'll keep the issue open to add a index.html that explains this.

**Comment by richardcase** [comment]
Great, thanks @thomaspoignant . I didn't think to try that....all working for me. Thank you.

**Comment by thomaspoignant** [comment]
Glad to hear that it works for you !
